"""add user_id to cart

Revision ID: d5f5f0de589e
Revises: 970dbaf0d37e
Create Date: 2026-04-03 18:25:09.281143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5f5f0de589e'
down_revision: Union[str, Sequence[str], None] = '970dbaf0d37e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('user_id', sa.UUID(), nullable=True))
    op.alter_column('carts', 'session_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_carts_user_id'), 'carts', ['user_id'], unique=True)
    op.create_foreign_key(None, 'carts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'carts', type_='foreignkey')
    op.drop_index(op.f('ix_carts_user_id'), table_name='carts')
    op.alter_column('carts', 'session_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('carts', 'user_id')
    # ### end Alembic commands ###
